Ristrutturazione classi con JwtAuthority
SWEasabi/authentication-micro-service pull request #8
Opened 2023-05-31 15:12 UTC by bonni1207

Close #7

2023-06-06 19:24 UTC, alessandro-massarenti requested changes
Vedi i commenti singoli, per il resto se è aderente alla specifica architetturale per me va bene.

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/SWEasabiAuthRest/Controller.java
> +		core = new CoreAuthService(usersService, keysService, blacklistService);
Sta roba andrebbe gestita con un dependency injector, magari direttamente quello di Spring

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/SWEasabiAuthRest/Controller.java
> +	BlacklistService blacklistService = new LocalBlacklistService();
Questa cosa crea una dipendenza particolarmente forte.

Si sta dicendo che senza la rest port il core auth service non può esistere. La cosa chiaramente non è normale, non va bene.

Dobbiamo definirla meglio architetturalmente.

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtAuthority.java
> +    }
```suggestion
    public JwtAuthority(KeysService keysService, BlacklistService blacklistService)
    {
        this.keysService =  keysService;
        this.blacklistService =  blacklistService;
    }
```

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtAuthority.java
> +    private BlacklistService blacklistService;
```suggestion
    private KeysService keysService ;
    private BlacklistService blacklistService;
```

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtAuthority.java
> +    }
```suggestion
    public JwtAuthority(KeysService ks , BlacklistService bs)
    {
        keysService = ks;
        blacklistService = bs;
    }
```

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtAuthority.java
Controlla anche il resto delle variabili se le modifichi

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtIssuer.java
Anche qui, occio ai nomi delle variabili

2023-06-06 19:24 UTC, alessandro-massarenti commented on src/main/java/it/SWEasabi/authentication/kernel/JwtVerifier.java
Anche qui, occhio ai nomi delle variabili

2023-07-21 19:08 UTC, bonni1207 commented on src/main/java/it/SWEasabi/SWEasabiAuthRest/Controller.java
> +		core = new CoreAuthService(usersService, keysService, blacklistService);
Dovrebbe farlo @casYy teoricamente

2023-08-12 13:55 UTC, merged